In [1]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr+2)

[3 4 5 6 7]


In [2]:
print(arr*3)

[ 3  6  9 12 15]


In [3]:
print(arr/2)

[0.5 1.  1.5 2.  2.5]


In [4]:
reversedArr=arr[::-1]
print(reversedArr)

[5 4 3 2 1]


In [5]:
x=np.array([1,2,3,4,5,1,2,1,1,1])
y=np.array([1,1,1,2,3,4,2,4,3,3])
print(np.bincount(x).argmax())
print(np.bincount(y).argmax())

1
1


In [6]:
arr1=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(arr1[0,1])

20


In [7]:
print(arr1[2,1])

80


In [8]:
james=np.linspace(10,100,num=25)
print(james)
print(james.ndim)
print(james.shape) #1d array
print(james.size)
print(james.dtype)
print(james.nbytes)
transpose=np.reshape(25,1)
print(transpose)

[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
1
(25,)
25
float64
200
[25]


In [20]:
john=np.array([[10,20,30,40],[50,60,70,80],[90,15,20,35]])
print(np.mean(john))
print(np.median(john))
print(np.max(john))
print(np.min(john))
print(np.unique(john))
reshaped_john=np.reshape(john,(4,3))
print(reshaped_john)
resized_john=np.resize(john,(2,3))
print(resized_john)

43.333333333333336
37.5
90
10
[10 15 20 30 35 40 50 60 70 80 90]
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
[[10 20 30]
 [40 50 60]]
